#!/usr/bin/python3

# This script takes the .po files from Weblate, and injects the translated
# messages into the default asset pack in the form of configuration files.

import datetime
import sys

def add_config(configs, loc, msg, locale):
    spl = loc.split(":")
    asset_path = spl[0]
    key_index = spl[1]

    path_split = asset_path.rsplit("/", 1)
    config_path = path_split[0] + "/config." + locale + ".cfg"
    asset_name = path_split[1]

    key = ""
    if key_index == "1":
        key = "name"
    elif key_index == "2":
        key = "desc"
    
    if not config_path in configs:
        configs[config_path] = {}
    
    if not asset_name in configs[config_path]:
        configs[config_path][asset_name] = {}
    
    configs[config_path][asset_name][key] = msg

if len(sys.argv) < 2:
    sys.exit("Need a locale as an argument.")

locale = sys.argv[1]
with open(locale + ".po", "r") as po_file:
    lines = po_file.readlines()
    
    configs = {}
    locs = []
    for line in lines:
        if line[0:2] == "#:":
            locs = ["../" + x.strip() for x in line.split("../")[1:]]
        
        elif line[0:6] == "msgstr" and len(locs) > 0:
            # TODO: Deal with new-lines within the message.
            msg = line[6:].strip()
            if msg[0] == '"' and msg[-1] == '"':
                msg = msg[1:-1]
            
            if len(msg) > 0:
                for loc in locs:
                    add_config(configs, loc, msg, locale)
    
    for config_path in configs:
        with open(config_path, "w") as config_file:
            print(config_path)
            creation_date = datetime.datetime.now()
            creation_date_str = creation_date.strftime("%Y-%m-%d %H:%M")
            config_file.write("; Generated by inject_po.py at {}\n".format(creation_date_str))

            for asset_name in configs[config_path]:
                config_file.write("[" + asset_name + "]\n")
                for key in configs[config_path][asset_name]:
                    value = configs[config_path][asset_name][key]
                    config_file.write(key + " = \"" + value + "\"\n")
                config_file.write("\n")
